@startuml
class Context
{
    - vk::Instance mVulkanInstance
    - vk::PhysicalDevice mPhysicalDevice
    - vk::Device mDevice
    - QueueFamilyIndicates mQueueFamilyIndicates

    - CreateInstance() : void
    - PickPhysicalDevice() : void
    - QueryQueueFamilyIndicates() : void
    - CreateLogicDevice() : void
    - GetQueues() : void
}
struct QueueFamilyIndicates
{
    + std::optional<uint32_t> graphicsFamily;
    + std::optional<uint32_t> graphicsFamilyCount;
    + std::optional<uint32_t> presentFamily;
    + std::optional<uint32_t> presentFamilyCount;
    + std::optional<uint32_t> transferFamily;
    + std::optional<uint32_t> transferFamilyCount;
}

Context -|> QueueFamilyIndicates
@enduml